define([
    'jquery',
    'lib/text!./viewDiyLocation.tpl.html',
    'common/webapi'
],function($,tpl,webapi){
    avalon.component('cap-view-diy-location-modal',{
        template:tpl,
        defaults:{
            show:false,
            title:'我的自定义',
            addr:{
                provinceName:'',
                cityName:'',
                districtName:'',
                name:'',
                address:'',
                createdDate:'',
                statusText:'',
                verifyMsg:''
            },
            setAddr:function(addr) {
                this.addr = addr;
            },
            onReady:function(){
                if(this.vmId!==undefined)this.vmId=this.$id;
            }
        }
    })
});