require.ensure([
    // './select/select',
    // './mini-cascader/mini-cascader',
    // './tab-cascader/tab-cascader',
    // './btnDropdown/btnDropdown',
    // './tagPicker/tagPicker',
    // './topMenu/topMenu',
    './header/header',
    // './menu/menu',
    // './date/date',
    // './fileUpload/fileInput',
    './tab/tab',
    // './photoUpload/photoUpload',
    // './modal/modal',
    // './modal/editRoute/editRoute',
    // './modal/editPricePolicy/editPricePolicy',
    // './modal/agreementDetail/agreementDetail',
    // './modal/discountDetail/discountDetail',
    // './modal/newFee/newFee',
    // './modal/newPreferentialFee/newPreferentialFee',
    // './modal/viewRoute/viewRoute',
    // './modal/previewRoute/previewRoute',
    // './modal/viewDiyLocation/viewDiyLocation',
    // './modal/auditDiyLocation/auditDiyLocation',
    // './modal/newDiyLocation/newDiyLocation',
    // './modal/viewPrice/viewPrice',
    // './modal/editPrice/editPrice',
    // './modal/viewDiscount/viewDiscount',
    // './modal/editDiscount/editDiscount',
    // './modal/chooseRoute/chooseRoute',
    // './modal/addressPick/addressPick',
    // './modal/imgPreview/imgPreview',
    // './modal/editPriceAndShipWeight/editPriceAndShipWeight'
],function () {
    
});